### ISSUE TITLE
No attribute Fill

### ISSUE THREAD

**Issue by BorisKourt** [adafruit/Adafruit_CircuitPython_IS31FL3731#2]
I am using a feather M0 simple, with a Matrix board.

When I try to run the following:

```python
import adafruit_is31fl3731
import board
import busio
with busio.I2C(board.SCL, board.SDA) as i2c:
    display = adafruit_is31fl3731.Matrix(i2c)
    display.fill(127)
```

I get 

```
AttributeError: 'Matrix' object has no attribute 'fill'
```

If I try to run the same code again in the same REPL session I get:

```
MemoryError: parser could not allocate enough memory
```

What am I doing wrong?

Thanks,
Boris

**Comment by tannewt** [comment]
I'm not sure about the memory error. That can depend a bit on the order that you do things. So, for that, please post everything you'd typed into the REPL.

For the `fill` issue, you've run into another doc problem. When I redid this library I changed it to have eight independent frames that you can edit. This allows you to switch quickly between multiple different designs really quickly. However, I didn't update the docs nor actually add the API to switch frames.

So, for now, you should be able to do `display.displayed_frame.fill(127)`. (`display.displayed_frame` is the same as `display.frames[0]`) I need to fix the ability to set display_frame to a different frame (`display.displayed_frame = display.frames[3]` for example). Right now I believe the object will be changed but the display won't update.

**Comment by BorisKourt** [comment]
Thanks for the clarification. Is this something I can contribute or would you rather do this yourself?

**Comment by tannewt** [comment]
I would love it if you'd do it. :-) I'm happy to help with any issues you have trying to do it. I'm also on [our Gitter chat](https://gitter.im/adafruit/circuitpython) most days and can help there as well.

**Comment by tannewt** [comment]
This issue came up on the experimental version which is no longer in master. It will be somewhat revived later but for now we can close this.
