### ISSUE TITLE
Update README to remove TODO

### ISSUE THREAD

**Issue by tannewt** [adafruit/Adafruit_CircuitPython_IS31FL3731#3]
Also get examples highlighted as Python

**Comment by tannewt** [comment]
The TODO is still there actually but the code is highlighted. The TODO should not only be removed but replaced with a description of the hardware the driver supports.

**Comment by process1183** [comment]
It looks like I somehow accidentally re added the TODO in the syntax highlighting commit (707be7bc14dc304ceb8c9ca8fa92f521e1c551aa), which I made after committing the TODO remove (fc69fefdad8e951dca2bcfdc3e898d97b43716a0). Oops.

**Comment by process1183** [comment]
I'm working on replacing the "TODO" with a short description and supported hardware. How does this look?

    CircuitPython driver for the IS31FL3731 charlieplex IC.
    
    This driver supports the following hardware:
    
    * `Adafruit 16x9 Charlieplexed PWM LED Matrix Driver - IS31FL3731 <https://www.adafruit.com/product/2946>`_
    * `Adafruit 15x7 CharliePlex LED Matrix Display FeatherWings <https://www.adafruit.com/product/2965>`_

**Comment by tannewt** [comment]
Looks great! Thanks!

**Comment by tannewt** [comment]
Done in https://github.com/process1183/Adafruit_CircuitPython_IS31FL3731/commit/cb21ee2fe22a8496adfa076d6bbb9dea8ff1204a. Thanks @process1183
