### ISSUE TITLE
"fade" method throws Exception when both params are None

### ISSUE THREAD

**Issue by EAGrahamJr** [adafruit/Adafruit_CircuitPython_IS31FL3731#52]
https://github.com/adafruit/Adafruit_CircuitPython_IS31FL3731/blob/97eb72a132f0a1349b2276cbc39539725f90515f/adafruit_is31fl3731/__init__.py#L193

It seems there's a missing `return` that should occur when both parameters are `None`. If that does **not** occur, line 209 will (obviously) fail.

**Comment by tannewt** [comment]
Would you mind making a PR? I think you are right what the fix is. https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github
